In [1]:
import numpy as np

In [2]:
from scipy import linalg

In [7]:
A=np.array([[1,-1],[0,1], [1,0], [-1,1], [1,1]])
#linalg.svd(A)


U, s, Vt = linalg.svd(A, full_matrices=False)
print('Matrix U\n',U)
print('vector s\n',s)
print('Matrix Vt\n',Vt)

Matrix U
 [[-6.32455532e-01  1.11022302e-16]
 [ 3.16227766e-01 -4.08248290e-01]
 [-3.16227766e-01 -4.08248290e-01]
 [ 6.32455532e-01 -1.11022302e-16]
 [-5.55111512e-17 -8.16496581e-01]]
vector s
 [2.23606798 1.73205081]
Matrix Vt
 [[-0.70710678  0.70710678]
 [-0.70710678 -0.70710678]]


In [14]:
U=np.array([[0,(-1)*pow(2,0.5)]])
S=np.array([[2.236, 0], [0,1]])
V=np.array([[-0.707,0.707],[-0.707,-0.707]])

D=U@S
E=D@V

print(E)

[[0.99984899 0.99984899]]


In [12]:
pow(64,0.5)

8.0