In [1]:
import matplotlib as plt

In [2]:
import numpy as np

In [4]:
x = np.array([2, 3.5, 4, 5.1, 7])
y = np.array([2.2, 2, 3, 6, 5])

plt(x,y)

TypeError: 'module' object is not callable

questao5

In [3]:
x5 = np.array([-4.501, 83.453, 112.953, 123.824, 170.335, 183.008])

In [5]:
somaX = x5.sum()

array([ -4.501,  83.453, 112.953, 123.824, 170.335, 183.008])

In [17]:
a1 = (x5**2).sum()

In [22]:
y = np.array([1,2,3,4,5,6])

In [10]:
lnx = np.log( x5)

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


In [19]:
a4=(lnx**2).sum()

In [20]:
a2=(x5*lnx).sum()

In [23]:
y1 = (x5*y).sum()
y1

2946.2830000000004

In [25]:
y2 = (lnx*y).sum()
y2

99.25094205485057

In [26]:
A=np.array([[a1,a2],[a2,a4]])
b = np.array([y1,y2])

In [27]:
beta = np.linalg.solve(A,b)
beta

array([ 0.03842302, -0.24128611])

In [3]:
x = np.array([2, 3.5, 4, 5.1, 7])
y = np.array([2.2, 2, 3, 6, 5])

In [8]:
a1 = x.size
a1

5

In [5]:
a2 = x.sum()
a2

21.6

In [9]:
a4 = (x**2).sum()
a4

107.25999999999999

In [11]:
y1 = y.sum()
y1

18.2

In [13]:
y2 = (x*y).sum()
y2

89.0

In [14]:
A=np.array([[a1,a2],[a2,a4]])
b = np.array([y1,y2])

In [15]:
beta = np.linalg.solve(A,b)
beta

array([0.42632636, 0.74390594])