In [1]:
import numpy as np
import math

In [2]:
def aproxOrtonormErroFrobIdentidade(m):
    #(i)
    W = np.random.randn(m,4)
    #(ii)
    Wnormalized = W / math.sqrt(m)
    #(iii)
    Z = Wnormalized.T @ Wnormalized
    #print(Z)
    #(iv)
    frobenius_Z_I = np.linalg.norm(Z-np.eye(4), ord='fro') 
    return frobenius_Z_I;

In [3]:
funcaoEx1(100)

NameError: name 'funcaoEx1' is not defined

In [ ]:
maior = 0
menor = 0
soma = 0

for i in range(1,100000):
    x = funcaoEx1(10000)
    if(x>maior):
        maior = x
    if(x<menor):
        menor = x
    soma+=x
    
    
        
print("maior", maior)
print("menor", menor)
print("media", soma/100000)

In [ ]:
maior = 0
menor = 0
soma = 0

for i in range(1,100000):
    x = funcaoEx1(100)
    if(x>maior):
        maior = x
    if(x<menor):
        menor = x
    soma += x
        
print("maior", maior)
print("menor", menor)
print("media", soma/100000)

In [ ]:
m = 10
np.set_printoptions(precision=2) 
W = np.random.randn(m,4)
print(W)
print()
print()
print()
print()
Wnormalized = W / math.sqrt(m)
print(Wnormalized)
print()
print()
print()
print()
Z = Wnormalized.T @ Wnormalized
print(Z)

In [ ]:
funcaoEx1(4)

In [ ]:
funcaoEx1(4)

In [ ]:
funcaoEx1(4)

In [ ]:
funcaoEx1(4)

In [ ]:
Y = np.array([[1,2],[3,4]])
print(Y/2)

In [ ]:
np.eye(4)

In [84]:
X = np.array([[90, 80, 60, 95],
              [65, 75, 90, 70],
              [40, 90, 60, 55],
              [80, 60, 59, 75],
              [60, 100, 80, 80]])
             

In [85]:
X = X.T

In [88]:
m,n = X.shape
mu = np.mean(X,axis=1)
Mu = np.reshape(np.repeat(mu,n),(m,n))
X_centered = (X-Mu)
X_cov = X_centered@X_centered.T

In [89]:
X_cov/4

array([[ 370.  , -165.  ,  -53.25,  243.75],
       [-165.  ,  230.  ,   55.25,  -18.75],
       [ -53.25,   55.25,  205.2 ,  -12.5 ],
       [ 243.75,  -18.75,  -12.5 ,  212.5 ]])

In [7]:
#np . s e t p r i n t o p t i o n s ( p r e c i s i o n =1)
np.cov (X.T, ddof =1)

array([[ 370.  , -165.  ,  -53.25,  243.75],
       [-165.  ,  230.  ,   55.25,  -18.75],
       [ -53.25,   55.25,  205.2 ,  -12.5 ],
       [ 243.75,  -18.75,  -12.5 ,  212.5 ]])

In [17]:
X@X.T

array([[27125, 23900, 19625, 22665, 25800],
       [23900, 22850, 18600, 20260, 24200],
       [19625, 18600, 16325, 16265, 20600],
       [22665, 20260, 16265, 19106, 21520],
       [25800, 24200, 20600, 21520, 26400]])

In [35]:
X = X.T

In [38]:
m,n = X.shape
mu = np.mean(X,axis=1)
# Alternativa 1
Mu = mu.repeat(n).reshape((m,n))
# Alternativa 2
Mu = np.reshape(np.repeat(mu,n),(m,n))
Mu

array([[81.25, 81.25, 81.25, 81.25],
       [75.  , 75.  , 75.  , 75.  ],
       [61.25, 61.25, 61.25, 61.25],
       [68.5 , 68.5 , 68.5 , 68.5 ],
       [80.  , 80.  , 80.  , 80.  ]])

In [39]:
X_centered = X-Mu
X_centered

array([[  8.75,  -1.25, -21.25,  13.75],
       [-10.  ,   0.  ,  15.  ,  -5.  ],
       [-21.25,  28.75,  -1.25,  -6.25],
       [ 11.5 ,  -8.5 ,  -9.5 ,   6.5 ],
       [-20.  ,  20.  ,   0.  ,   0.  ]])

In [44]:
X_centered = X/4

In [46]:
X_centered.T@X_centered

array([[1495.3125, 1654.6875, 1448.125 , 1631.25  ],
       [1654.6875, 2107.8125, 1780.625 , 1893.75  ],
       [1448.125 , 1780.625 , 1573.8125, 1632.8125],
       [1631.25  , 1893.75  , 1632.8125, 1810.9375]])

In [12]:
np.sum(X_centered[1,:])

0.0

In [13]:
sigma = np.std(X_centered, axis=1)
sigma

array([17.20465053, 13.56465997, 12.8124939 , 13.03840481])

In [14]:
Sigma = sigma.repeat(n).reshape((m,n))
X_normalized = X_centered/Sigma
X_normalized

array([[ 1.33684785, -0.11624764, -1.56934312,  0.75560965, -0.40686674],
       [-0.07372098, -0.44232587,  0.6634888 , -1.54814054,  1.40069858],
       [-0.76487841,  1.57658612, -0.76487841, -0.84292723,  0.79609794],
       [ 1.53392998, -0.38348249, -1.53392998,  0.        ,  0.38348249]])

In [ ]:
print(Sigma)

In [15]:
X_normalized@X_normalized.T

array([[ 5.        , -2.82806358, -0.96627352,  4.34644611],
       [-2.82806358,  5.        ,  1.27159757, -0.42406057],
       [-0.96627352,  1.27159757,  5.        , -0.29930355],
       [ 4.34644611, -0.42406057, -0.29930355,  5.        ]])

In [ ]:
ortogonal = np.array([[1,1,1],
                      [1,0,-2],
                      [1,-1,1]])
print(ortogonal@ortogonal.T)

In [ ]:
import math

In [ ]:
x = 1/math.sqrt(3)
y = 1/math.sqrt(2)
z = 1/math.sqrt(6)

ortonormal = np.array([[x,y,z],
                      [x,0,(-2*z)],
                      [x,-y,z]])
print(ortonormal@ortonormal.T)